# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
git:
  paging:
    colorArg: always
    pager: delta --paging=never
  pull:
    mode: 'rebase' # one of 'merge' | 'rebase' | 'ff-only'
os:
  edit: 'nvim'
  editAtLine: '{{editor}} +{{line}} -- {{filename}}'
  open: zed {{filename}}
reporting: "off"
startuppopupversion: 1
