# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --features=decorations
  pull:
    mode: 'rebase' # one of 'merge' | 'rebase' | 'ff-only'
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim --line={{line}} {{filename}}'
  editAtLineAndWait: 'nvim --block --line={{line}} {{filename}}'
  editInTerminal: true
