#!/usr/bin/env zsh

brew tap "homebrew/bundle"
brew tap "homebrew/cask"
brew tap "homebrew/core"

brew install "asdf"
brew install "curl"
brew install "wget"
brew install "bat"
brew install "exa"
brew install "fd"
brew install "ripgrep"
brew install "peco"
brew install "lf"

brew install "fzf"
brew install "gh"
brew install "git"
brew install "git-delta"
brew install "gpg"
brew install "httpie"
brew install "htop"
brew install "neovim"
brew install "stylua"
brew install "oath-toolkit"
brew install "task"
brew install "timewarrior"
brew install "tmux"
brew install "trash"
brew install "jesseduffield/lazygit/lazygit"

brew install --cask "kitty"
brew install --cask "iterm2"
brew install --cask "docker"
brew install --cask "hammerspoon"
brew install --cask "karabiner-elements"
brew install --cask "appcleaner"
brew install --cask "the-unarchiver"
brew install --cask "clashx"
brew install --cask "telegram"
brew install --cask squirrel
