tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "python@3.9"
brew "autojump"
brew "bat"
brew "ccat"
brew "diff-so-fancy"
brew "efm-langserver"
brew "fd"
brew "file-formula"
brew "fzf"
brew "gh"
brew "git"
brew "git-flow"
brew "gnutls"
brew "gnupg"
brew "highlight"
brew "httpie"
brew "htop"
brew "k3d"
brew "lazygit"
brew "libpng"
brew "libzzip"
brew "lolcat"
brew "lsd"
brew "luajit", args: ["HEAD"]
brew "maven"
brew "neovim", args: ["HEAD"]
brew "oath-toolkit"
brew "python@3.8"
brew "ranger"
brew "ripgrep"
brew "ruby"
brew "task"
brew "timewarrior"
brew "the_silver_searcher"
brew "tmux"
brew "watchman"
brew "wget"
brew "z"
brew "jesseduffield/lazynpm/lazynpm"
cask "docker"
cask "font-fantasque-sans-mono"
cask "font-source-code-pro-for-powerline"
cask "hammerspoon"
cask "karabiner-elements"
cask "kitty"
cask "postman"
cask "appcleaner"

mas "Amphetamine", id: 937984704
mas "The Unarchiver", id: 425424353
