tap "daipeihust/tap"
tap "oven-sh/bun"
tap "jesseduffield/lazygit"
brew "antidote"
brew "bat"
brew "btop"
brew "cmake"
brew "cowsay"
brew "curl"
brew "duf"
brew "docker"
brew "docker-compose"
brew "fortune"
brew "eza"
brew "fd"
brew "fzf"
brew "ffmpeg"
brew "fish"
brew "fisher"
brew "gawk"
brew "git"
brew "git-delta"
brew "glow"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "mise"
brew "imagemagick"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "resvg"
brew "sevenzip"
brew "slides"
brew "stylua"
brew "tokei"
brew "typos"
brew "trash", link: true
brew "wget"
brew "yazi"
brew "yt-dlp"
brew "zoxide"
brew "daipeihust/tap/im-select"
brew "jesseduffield/lazygit/lazygit"
brew "oven-sh/bun/bun"
cask "bitwarden"
cask "brave-browser"
cask "clash-verge-rev"
cask "discord"
cask "font-maple-mono-nf-cn"
cask "google-chrome"
cask "kitty"
cask "localsend"
cask "rapidapi"
cask "raycast"
# cask "squirrel"
cask "the-unarchiver"
cask "telegram"
cask "visual-studio-code"
cask "input-source-pro"
cask "iina"
# cask "figma"
# cask "linear-linear"
cask "obsidian"
cask "orbstack"
# cask "shottr"
# cask "slack"


