#!/usr/bin/env zsh

brew tap "homebrew/bundle"
brew tap "homebrew/cask"
brew tap "homebrew/core"

brew install "asdf"
brew install "bat"
brew install "curl"
brew install "exa"
brew install "fd"
brew install "fzf"
brew install "gh"
brew install "git"
brew install "git-delta"
brew install "gpg"
brew install "htop"
brew install "httpie"
brew install "jesseduffield/lazygit/lazygit"
brew install "lf"
brew install "most"
brew install "neovim"
brew install "ripgrep"
brew install "stylua"
brew install "tmux"
brew install "trash"
brew install "wget"

brew install --cask "kitty"
brew install --cask "iterm2"
brew install --cask "docker"
brew install --cask "hammerspoon"
brew install --cask "karabiner-elements"
brew install --cask "appcleaner"
brew install --cask "the-unarchiver"
brew install --cask "clashx"
brew install --cask "telegram"
brew install --cask squirrel
