"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$docker_context\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[git_branch]
symbol = " "
