require("indent_blankline").setup {
    filetype = {
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "html",
        "css",
        "scss",
        "sass",
        "less",
        "lua",
        "go",
        "ruby",
        "erb",
        "rust",
        "json",
        "yaml",
        "toml",
        "scheme",
    },
    buftype_exclude = { "terminal", "telescope", "prompt", "nofile" },
    use_treesitter = true,
    show_current_context = true,
    show_current_context_start = false,
    show_trailing_blankline_indent = false,
}
