require("indent_blankline").setup {
    char = "┆",
    show_first_indent_level = false,
    filetype = {
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "html",
        "css",
        "scss",
        "sass",
        "lua",
        "go",
        "ruby",
        "erb",
        "rust",
        "json",
        "yaml",
        "toml",
        "scheme",
    },
    buftype_exclude = { "terminal", "telescope" },
}
