[default_view]

keymap = [
  { keys = [ "escape" ],      command = "escape" },
  { keys = [ "ctrl+t" ],      command = "new_tab --current" },
  { keys = [ "ctrl+w" ],      command = "close_tab" },
  { keys = [ "ctrl+c" ],      command = "quit" },
  { keys = [ "q" ],           command = "quit --output-selected-files" },
  { keys = [ "Q" ],           command = "quit --force" },
  # { keys = [ "T" ],           command = "new_tab --cursor" },

  { keys = [ "f5" ],          command = "reload_dirlist" },
  { keys = [ "ctrl+h" ],      command = "toggle_hidden" },
  { keys = [ "\t" ],          command = "tab_switch 1" },
  { keys = [ "backtab" ],     command = "tab_switch -1" },

  { keys = [ "alt+1" ],       command = "tab_switch_index 1" },
  { keys = [ "alt+2" ],       command = "tab_switch_index 2" },
  { keys = [ "alt+3" ],       command = "tab_switch_index 3" },
  { keys = [ "alt+4" ],       command = "tab_switch_index 4" },
  { keys = [ "alt+5" ],       command = "tab_switch_index 5" },

  { keys = [ "1" ],           command = "numbered_command 1" },
  { keys = [ "2" ],           command = "numbered_command 2" },
  { keys = [ "3" ],           command = "numbered_command 3" },
  { keys = [ "4" ],           command = "numbered_command 4" },
  { keys = [ "5" ],           command = "numbered_command 5" },
  { keys = [ "6" ],           command = "numbered_command 6" },
  { keys = [ "7" ],           command = "numbered_command 7" },
  { keys = [ "8" ],           command = "numbered_command 8" },
  { keys = [ "9" ],           command = "numbered_command 9" },

  # vim-like keybindings
  { keys = [ "j" ],           command = "cursor_move_down" },
  { keys = [ "k" ],           command = "cursor_move_up" },
  { keys = [ "h" ],           command = "cd .." },
  { keys = [ "l" ],           command = "open" },
  { keys = [ "g", "g" ],      command = "cursor_move_home" },
  { keys = [ "G" ],           command = "cursor_move_end" },
  { keys = [ "o" ],           command = "quit --output-current-directory" },

  { keys = [ "H" ],           command = "cursor_move_page_home" },
  { keys = [ "L" ],           command = "cursor_move_page_middle" },
  { keys = [ "M" ],           command = "cursor_move_page_end" },
  { keys = [ "[" ],           command = "parent_cursor_move_up" },
  { keys = [ "]" ],           command = "parent_cursor_move_down" },
  { keys = [ "ctrl+u" ],      command = "cursor_move_page_up 0.5" },
  { keys = [ "ctrl+d" ],      command = "cursor_move_page_down 0.5" },

  { keys = [ "c", "d" ],      command = ":cd " },
  { keys = [ "a" ],           command = ":touch " },
  { keys = [ "A" ],           command = ":mkdir " },
  { keys = [ "x" ],           command = "cut_files" },
  { keys = [ "d" ],           command = "delete_files" },
  { keys = [ "r" ],           command = "rename_append" },
  { keys = [ "R" ],           command = "rename_prepend" },

  { keys = [ "y", "y" ],      command = "copy_files" },
  { keys = [ "y", "n" ],      command = "copy_filename" },
  { keys = [ "y", "." ],      command = "copy_filename_without_extension" },
  { keys = [ "y", "p" ],      command = "copy_filepath" },
  { keys = [ "y", "d" ],      command = "copy_dirpath" },

  { keys = [ "p", "l" ],      command = "symlink_files --relative=false" },
  { keys = [ "p", "L" ],      command = "symlink_files --relative=true" },

  { keys = [ "p", "p" ],      command = "paste_files" },
  { keys = [ "p", "o" ],      command = "paste_files --overwrite=true" },

  { keys = [ " " ],           command = "select --toggle=true" },
  { keys = [ "t" ],           command = "select --all=true --toggle=true" },
  { keys = [ "V" ],           command = "toggle_visual"},

  { keys = [ "w" ],           command = "show_tasks --exit-key=w" },
  { keys = [ "b", "b" ],      command = "bulk_rename" },
  { keys = [ "=" ],           command = "set_mode" },

  { keys = [ ":" ],           command = ":" },
  { keys = [ ";" ],           command = ":shell" },

  { keys = [ "/" ],           command = ":search_inc " },
  { keys = [ "|" ],           command = ":search " },
  { keys = [ "\\" ],          command = ":search_glob " },
  { keys = [ "S" ],           command = "search_fzf" },
  { keys = [ "ctrl+f" ],      command = "subdir_fzf" },
  { keys = [ "f" ],           command = ":filter " },
  { keys = [ "z" ],           command = "zi" },

  { keys = [ "n" ],           command = "search_next" },
  { keys = [ "N" ],           command = "search_prev" },

  { keys = [ "s", "r" ],      command = "sort reverse" },
  { keys = [ "s", "l" ],      command = "sort lexical" },
  { keys = [ "s", "m" ],      command = "sort mtime" },
  { keys = [ "s", "n" ],      command = "sort natural" },
  { keys = [ "s", "s" ],      command = "sort size" },
  { keys = [ "s", "e" ],      command = "sort ext" },

  # { keys = [ "m", "s" ],      command = "linemode size" },
  # { keys = [ "m", "m" ],      command = "linemode mtime" },
  # { keys = [ "m", "M" ],      command = "linemode sizemtime" },

  { keys = [ "'" ],           command = "cd_bookmark" },
  { keys = [ "m" ],           command = "add_bookmark" },

  # arrow keys
  { keys = [ "arrow_up" ],    command = "cursor_move_up" },
  { keys = [ "arrow_down" ],  command = "cursor_move_down" },
  { keys = [ "arrow_left" ],  command = "cd .." },
  { keys = [ "arrow_right" ], command = "open" },
  { keys = [ "\n" ],          command = "open" },
  { keys = [ "insert" ],      command = ":touch" },
  { keys = [ "delete" ],      command = "delete_files" },
  { keys = [ "home" ],        command = "cursor_move_home" },
  { keys = [ "end" ],         command = "cursor_move_end" },
  { keys = [ "page_up" ],     command = "cursor_move_page_up" },
  { keys = [ "page_down" ],   command = "cursor_move_page_down" },
  { keys = [ "?" ],           command = "help" },
]

[task_view]

keymap = [
  # arrow keys
  { keys = [ "arrow_up" ],   command = "cursor_move_up" },
  { keys = [ "arrow_down" ], command = "cursor_move_down" },
  { keys = [ "home" ],       command = "cursor_move_home" },
  { keys = [ "end" ],        command = "cursor_move_end" },

  # vim-like keybindings
  { keys = [ "j" ],          command = "cursor_move_down" },
  { keys = [ "k" ],          command = "cursor_move_up" },
  { keys = [ "g", "g" ],     command = "cursor_move_home" },
  { keys = [ "G" ],          command = "cursor_move_end" },

  { keys = [ "w" ],          command = "show_tasks" },
  { keys = [ "escape" ],     command = "show_tasks" },
]

[help_view]

keymap = [
  # arrow keys
  { keys = [ "arrow_up" ],   command = "cursor_move_up" },
  { keys = [ "arrow_down" ], command = "cursor_move_down" },
  { keys = [ "home" ],       command = "cursor_move_home" },
  { keys = [ "end" ],        command = "cursor_move_end" },

  # vim-like keybindings
  { keys = [ "j" ],          command = "cursor_move_down" },
  { keys = [ "k" ],          command = "cursor_move_up" },
  { keys = [ "g", "g" ],     command = "cursor_move_home" },
  { keys = [ "G" ],          command = "cursor_move_end" },

  { keys = [ "w" ],          command = "show_tasks" },
  { keys = [ "escape" ],     command = "show_tasks" },
]
