alias ..   "cd .."
alias ...  "cd ../.."
alias .... "cd ../../.."
alias ls   "lsd"
alias ll   "ls -l"
alias la   "ls -la"
alias lt   "ls --tree"
alias rm   "trash -v"

alias gsb   "git status -sb"
alias gundo "git reset HEAD~"

alias v  "nvim +SessionLoad"
alias n  "pnpm"
alias ni "pnpm i"
alias ns "pnpm run start"
alias nd "pnpm run dev"
alias nt "pnpm run test"
alias nlsg "npm list -g --depth=0"

alias t="task"
alias tl="task list"
alias tc="task done"
alias ta="task add"
alias td="task del"
