vim.g.mapleader = " "

map("n|<esc>", ":noh<CR><ESC>")
map("n|q", "")
map("n|Q", "q")
map("n|<C-q>", "")
map("n|k", [[(v:count == 0 ? 'gk' : 'k')]], { expr = true })
map("n|j", [[(v:count == 0 ? 'gj' : 'j')]], { expr = true })
map("v|p", '"_dp')
map("n|H", "^")
map("n|L", "g_")
map("v|H", "^")
map("v|L", "g_")
map("v|<", "<gv")
map("v|>", ">gv")
map("n|<", "<<")
map("n|>", ">>")

map("i|<C-a>", "<C-o>^")
map("c|<C-a>", "<HOME>")
map("!|<C-b>", "<Left>")
map("!|<C-e>", "<END>")
map("!|<C-f>", "<Right>")
map("i|<C-k>", "<C-o>dg_")
map("!|<C-v>", "<C-r>*")
map("n|<C-h>", [[<c-w>h]])
map("n|<C-l>", [[<c-w>l]])
map("n|<C-j>", [[<c-w>j]])
map("n|<C-k>", [[<c-w>k]])
map("t|<C-H>", [[<c-\><c-n><c-w>h]])
map("t|<C-L>", [[<c-\><c-n><c-w>l]])
map("t|<C-J>", [[<c-\><c-n><c-w>j]])
map("t|<C-K>", [[<c-\><c-n><c-w>k]])
map("t|<C-]>", [[<C-\><C-n>]])

map("n|]w", "g*")
map("n|[w", "g#")
map("v|]w", "g*")
map("v|[w", "g#")

map_cmd("n|\\q", ":copen")
map_cmd("n|<bs>q", ":cclose")

map("x|<c-k>", ":move '<-2<CR>gv-gv")
map("x|<c-j>", ":move '>+1<CR>gv-gv")
map("n|<leader><bs>", '"_dd')

map("i|<C-s>", "<C-o><cmd>w<cr>")
map("i|<M-s>", "<C-o><cmd>w<cr>")
map("n|<C-s>", [[empty(expand('%:t')) ? ":w\<Space>" : ":w\<CR>"]], { expr = true })
map("n|<M-s>", [[empty(expand('%:t')) ? ":w\<Space>" : ":w\<CR>"]], { expr = true })

map("n|<C-q>o", [[:lua searching_google(vim.fn.expand("<cword>"))<CR>]])
map("n|<C-q>t", [[:lua searching_deepl(vim.fn.expand("<cword>"))<CR>]])
map("v|<C-q>o", [[<ESC>gv"gy<ESC>:lua searching_google(vim.fn.getreg('g'))<CR>]])
