vim.g.mapleader = " "

map("n|<Space>", "")
map("x|<Space>", "")
map("n|q", "")
map("n|Q", "q")
map("n|<C-q>", "")
map("n|H", "^")
map("v|H", "^")
map("n|L", "$")
map("v|L", "g_")
map("n|n", "'Nn'[v:searchforward]", { expr = true })
map("n|N", "'nN'[v:searchforward]", { expr = true })
map("n|k", [[(v:count == 0 ? 'gk' : 'k')]], { expr = true })
map("n|j", [[(v:count == 0 ? 'gj' : 'j')]], { expr = true })
map("n|<ESC>", ":noh<CR><ESC>")

map("i|<C-a>", "<C-o>^")
map("c|<C-a>", "<HOME>")
map("!|<C-b>", "<Left>")
map("!|<C-e>", "<END>")
map("i|<C-d>", "<delete>")
map("!|<C-f>", "<Right>")
map("i|<C-h>", "<bs>")
map("i|<C-k>", "<C-o>dg_")
map("i|<C-u>", "<C-o>d^")
map("!|<C-v>", "<C-r>*")
map("i|<C-s>", "<C-o><cmd>w<cr>")
map("i|<M-s>", "<C-o><cmd>w<cr>")
map("i|<S-Tab>", "<bs>")
map("i|,", ",<C-g>u")
map("i|.", ".<C-g>u")
map("i|!", "!<C-g>u")
map("i|?", "?<C-g>u")

map("t|<C-H>", [[<c-\><c-n><c-w>h]])
map("t|<C-L>", [[<c-\><c-n><c-w>l]])
map("t|<C-J>", [[<c-\><c-n><c-w>j]])
map("t|<C-K>", [[<c-\><c-n><c-w>k]])
map("t|<C-[>", [[<C-\><C-n>]])

map("n|<C-h>", [[<c-w>h]])
map("n|<C-l>", [[<c-w>l]])
map("n|<C-j>", [[<c-w>j]])
map("n|<C-k>", [[<c-w>k]])
map_cmd("n|<C-w><up>", "res -10")
map_cmd("n|<C-w><down>", "res +10")
map_cmd("n|<C-w><right>", "vertical resize -10")
map_cmd("n|<C-w><left>", "vertical resize +10")

map("n|<leader><bs>", '"_dd')
map("v|p", '"_dP')
map("n|<C-s>", [[empty(expand('%:t')) ? ":w\<Space>" : ":w\<CR>"]], { expr = true })
map("n|<M-s>", [[empty(expand('%:t')) ? ":w\<Space>" : ":w\<CR>"]], { expr = true })

map("n|]w", "g*")
map("n|[w", "g#")
map("v|]w", "g*")
map("v|[w", "g#")

map("x|K", ":move '<-2<CR>gv-gv")
map("x|J", ":move '>+1<CR>gv-gv")
map("v|<", "<gv")
map("v|>", ">gv")
map("n|<", "<<")
map("n|>", ">>")

map("n|<C-q>o", [[:lua searching_google(vim.fn.expand("<cword>"))<CR>]])
map("n|<C-q>t", [[:lua searching_deepl(vim.fn.expand("<cword>"))<CR>]])
map("v|<C-q>o", [[<ESC>gv"gy<ESC>:lua searching_google(vim.fn.getreg('g'))<CR>]])
