local tree_cb = require("nvim-tree.config").nvim_tree_callback
var_tbl({
    nvim_tree_width = 40,
    nvim_tree_indent_markers = 1,
    nvim_tree_follow = 0,
    nvim_tree_quit_on_open = 0,
    nvim_tree_git_hl = 1,
    nvim_tree_width_allow_resize = 1,
    nvim_tree_ignore = { ".git", ".cache", ".idea", ".DS_Store" },
    nvim_tree_special_files = { "README.md", "Makefile", "MAKEFILE" },
    nvim_tree_window_picker_exclude = {
        filetype = {
            "packer",
            "qf",
        },
        buftype = {
            "terminal",
            "help",
        },
    },
    nvim_tree_disable_default_keybindings = 1,
    nvim_tree_bindings = {
        { key = { "<CR>", "<2-LeftMouse>" }, cb = tree_cb("edit") },
        { key = { "<2-RightMouse>", "<C-]>" }, cb = tree_cb("cd") },
        { key = "<C-v>", cb = tree_cb("vsplit") },
        { key = "<C-x>", cb = tree_cb("split") },
        { key = "<C-t>", cb = tree_cb("tabnew") },
        { key = "<", cb = tree_cb("prev_sibling") },
        { key = ">", cb = tree_cb("next_sibling") },
        { key = "P", cb = tree_cb("parent_node") },
        { key = "<BS>", cb = tree_cb("close_node") },
        { key = "<S-CR>", cb = tree_cb("close_node") },
        { key = "<Tab>", cb = tree_cb("preview") },
        { key = "K", cb = tree_cb("first_sibling") },
        { key = "J", cb = tree_cb("last_sibling") },
        { key = "I", cb = tree_cb("toggle_ignored") },
        { key = "H", cb = tree_cb("toggle_dotfiles") },
        { key = "R", cb = tree_cb("refresh") },
        { key = "a", cb = tree_cb("create") },
        { key = "d", cb = tree_cb("remove") },
        { key = "r", cb = tree_cb("rename") },
        { key = "<C-r>", cb = tree_cb("full_rename") },
        { key = "x", cb = tree_cb("cut") },
        { key = "c", cb = tree_cb("copy") },
        { key = "p", cb = tree_cb("paste") },
        { key = "y", cb = tree_cb("copy_name") },
        { key = "Y", cb = tree_cb("copy_path") },
        { key = "gy", cb = tree_cb("copy_absolute_path") },
        { key = "[c", cb = tree_cb("prev_git_item") },
        { key = "]c", cb = tree_cb("next_git_item") },
        { key = "-", cb = tree_cb("dir_up") },
        { key = "o", cb = tree_cb("system_open") },
        { key = "q", cb = tree_cb("close") },
        { key = "g?", cb = tree_cb("toggle_help") },
        { key = "l", cb = tree_cb("edit") },
        { key = "h", cb = tree_cb("close_node") },
        { key = "<C-e>", cb = tree_cb("close") },
    },
    nvim_tree_icons = {
        default = "",
        symlink = "",
        git = {
            unstaged = font_icon.modifiy,
            staged = font_icon.add,
            unmerged = font_icon.merge,
            renamed = font_icon.renamed,
            untracked = font_icon.unknown,
            deleted = font_icon.deleted,
            ignored = font_icon.ignored,
        },
        folder = {
            default = "",
            open = "",
            empty = "",
            empty_open = "",
            symlink = "",
            symlink_open = "",
        },
    },
})

autocmd("BufEnter", "NvimTree", "exec 'NvimTreeRefresh'")

map_cmd("n|<C-e>", "NvimTreeToggle")
map_cmd("n|<C-E>", "NvimTreeFindFile")
