alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

alias vi="/usr/local/bin/nvim"
alias nv="/usr/local/bin/nvim"
alias ls="lsd"
alias ll="ls -l"
alias la="ls -la"
alias lt="ls --tree"
alias ra="ranger"
alias cat="ccat"
alias n="pnpm"
