alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

alias j="z"
alias c='pbcopy'
alias v="nvim"
alias vi="nvim"
alias ip="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"
alias ls="exa --long --header --git --modified --color-scale"
alias la="exa -la --long --header --git --modified --color-scale"
alias lt="tree -L 2"
alias rm="trash -v"

alias n="pnpm"
alias nlsg="npm list -g --depth=0"
alias y="yarn"
alias yb="yarn run build"
alias ys="yarn run start"
alias yd="yarn run dev"
alias yt="yarn run test"

alias sskq="bundle exec sidekiq -C config/sidekiq.yml"
alias rs="GRAPHQL_CONSUMER_ORIGINS='localhost:3001, localhost:1215' bundle exec rails s"
